config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
    root 'homes#top'
    get '/about' => 'homes#about'
    get '/search' => 'searches#search'
    get '/recipes/favorite' => 'recipes#favorite'
    resources :recipes, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :show]

    get 'unsubscribe/' => 'users#unsubscribe', as: 'confirm_unsubscribe'
    patch ':id/withdraw/' => 'users#withdraw', as: 'withdraw_user'
    put 'withdraw/' => 'users#withdraw'
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  is_impressionable counter_cache: true

  belongs_to :user
  belongs_to :genre
  has_many :recipe_tags, dependent: :destroy
  has_many :tags, through: :recipe_tags

  attachment :recipe_image
  validates :name, presence: true, length: { maximum: 20 }
  validates :recipe_image, :ingredient, :method, :cooking_time, :serve, :genre_id, presence: true
  validates :rate, presence: true, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1,
  }

  enum cooking_time: {
    '30分以下': 1, '60分以下': 2, '60分以上': 3, '半日以上': 4, '一晩': 5,
  }

  # 検索機能
  def self.search(keyword)
    return current_user.recipes() unless keyword
    Recipe.where(["name LIKE(?)", "#{keyword}%"])
  end

  # タグ機能
  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      tag = Tag.find_by(tag_name: old)
      self.recipe_tags.delete RecipeTag.find_by(tag_id: tag.id, recipe_id: self.id)
    end
    # ↑今あるタグを削除
    # ↓新しくタグを作る
    new_tags.each do |new|
      new_tag = Tag.find_or_create_by(tag_name: new)
      unless RecipeTag.exists?(tag_id: new_tag.id, recipe_id: self.id)
        new_recipe_tag = RecipeTag.create(tag_id: new_tag.id, recipe_id: self.id)
        self.recipe_tags << new_recipe_tag
      end
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  impressionist :actions => [:show]

  def index
    @genres = Genre.all
    @tag_list = Tag.all
    # ↓ジャンル検索
    if params[:genre_id]
      @genre = @genres.find(params[:genre_id])
      @recipes = @genre.recipes.where(user_id: current_user.id).page(params[:page]).per(6)
    # ↓タグ検索
    elsif params[:tag_id]
      @tag = Tag.find(params[:tag_id])
      @recipes = @tag.recipes.where(user_id: current_user.id).page(params[:page]).per(6)
      @recipe_tag = @tag.tag_name
    # ↓すべて
    else
      @recipes = current_user.recipes.page(params[:page]).per(6).order(id: "DESC")
    end
    @all_recipes_count = @recipes.total_count
  end

  def show
    @recipe = Recipe.find(params[:id])
    redirect_to users_path unless current_user == @recipe.user
    @recipe_tags = @recipe.tags
    impressionist(@recipe, nil, unique: [:ip_address])
  end

  def new
    @recipe = Recipe.new
    @genre_list = Genre.pluck('name, id')
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    tag_list = params[:recipe][:tag_name].split(nil)
    if @recipe.save
      @recipe.save_tag(tag_list)
      redirect_to recipe_path(@recipe.id), notice: "レシピを作成しました。"
    else
      @genre_list = Genre.pluck('name, id')
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @genre_list = Genre.pluck('name, id')
    if @recipe.user.id == current_user.id
      render :edit
    else
      redirect_to :recipes_path
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    @genres = Genre.all
    tag_list = params[:recipe][:tag_name].split(nil)
    if @recipe.update(recipe_params)
      @recipe.save_tag(tag_list)
      redirect_to recipe_path(@recipe.id), notice: 'レシピを更新しました。'
    else
      @genre_list = Genre.pluck('name, id')
      render :edit
    end
  end

  def destroy
    @recipe = current_user.recipes.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  def favorite
    @recipe = current_user.recipes.find(params[:id])
    if @recipe.favorite
      @recipe.update(favorite: false)
    else
      @recipe.update(favorite: true)
    end
  end

  private
  def recipe_params
    params.require(:recipe).permit(:name, :recipe_image, :ingredient, :method, :cooking_time, :serve, :memo, :genre_id, :rate)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_favorite.html.erb
<%= link_to recipes_favorite_path(id: @recipe.id), remote: true do %>
  <% if @recipe.favorite %>
    <i class="fas fa-heart text-danger"></i>
  <% else %>
    <i class="far fa-heart"></i>
  <% end %>
<% end %>

app/views/recipes/_search_field.html.erb
<div class="search-form">
  <form method="get" action="<%= search_path %>" class="search_container">
    <input type="text" name="keyword" size="60" placeholder="Search" class="text-field">
    <input type="submit" value="&#xf002">
  </form>
  <div class="recipe-results"></div>
</div>

app/views/recipes/_side_menu.html.erb
<div class="sidebar">
  <div class="index-genre">
    <h5>ジャンル検索</h5>
    <%= link_to "全レシピ", recipes_path %><br>
    <% genres.each do |genre| %>
      <%= link_to genre.name, recipes_path(genre_id: genre.id) %><br>
    <% end %>
  </div>
</div>

app/views/recipes/edit.html.erb
<!--エラーメッセージ-->
<% if @recipe.errors.any? %>
  <div class="container mt-5">
    <div class="form">
      <div class="error-box p-3">
        <h5 class=text-danger><%= @recipe.errors.count %>件のエラーが発生しました</h5>
        <ul class="ml-4">
          <% @recipe.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

<div class="container mt-5">
  <div class="row mb-3">
    <div class="col-md-12">
      <h3>Edit Recipe</h3>

      <%= form_with model: @recipe, local:true do |f| %>
        <div class="form">
          <div class="form-group mb-4">
            <%= f.label :name %><br/>
            <%= f.text_field :name, class: "form-control" %>
          </div>

          <div class="form-group mb-4">
            <%= f.label :recipe_image %><br/>
            <%= f.attachment_field :recipe_image %>
          </div>

          <div class="form-group mb-4">
            <%= f.label :ingredient %>
            <%= f.hidden_field :ingredient, id: :ingredient, class: "form-control" %>
            <trix-editor input="ingredient"></trix-editor>
          </div>

          <div class="form-group mb-4">
            <%= f.label :method %>
            <%= f.hidden_field :method, id: :method, class: "form-control" %>
            <trix-editor input="method"></trix-editor>
          </div>

          <div class="field mb-4">
            <%= f.label :serve %>
            <%= f.select :serve, options_for_select((1..10).to_a, selected:@recipe.serve)%>
          </div>

          <div class="form-group mb-4">
            <%= f.label :cooking_time %>
            <%= f.select :cooking_time, Recipe.cooking_times.keys, {prompt: "Select"} %>
          </div>

          <div class="form-group mb-4">
            <div id="star" class="form-group">
              <%= f.label :rate %>
              <%= f.hidden_field :rate, class:"form-control" %>
            </div>
            <script>
              $('#star').raty({
                size     : 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn :  '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                scoreName: 'recipe[rate]',
                half: true,
                score: <%= @recipe.rate %>
              });
            </script>
          </div>

          <div class="form-group mb-4">
            <%= f.label :memo %>
            <%= f.hidden_field :memo, id: :memo, class: "form-control" %>
            <trix-editor input="memo", placeholder= "コツや注意書きなど"></trix-editor>
          </div>

          <div class="form-group mb-4">
            <%= f.label :genre_id %><br/>
            <%= f.select :genre_id, @genre_list %>
          </div>

          <div class="form-group mb-4">
            <%= f.label :tag_name %><br/>
            <%= f.text_field :tag_name, class: "form-control", placeholder: "グルテンフリー バター不使用 など　(タグを複数つけるには半角スペースで区切ってください)" %>
          </div>
        </div>

        <div class="create-btn">
          <%= f.submit '編集保存', class:"btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!--トップに戻るボタン-->
<span id="back">
  <a href="#">
    <i class="fas fa-arrow-circle-up arrow"></i>
  </a>
</span>

app/views/recipes/favorite.js.erb
$("#favorite_<%= @recipe.id%>").html("<%= j(render 'recipes/favorite', recipe: @recipe) %>")

app/views/recipes/index.html.erb
<div class="container mt-5">
  <!--検索フィールド-->
  <div class="row mb-5">
    <div class="col-md-6 ml-auto">
      <%= render 'recipes/search_field' %>
    </div>
  </div>
  
  <!--サイドメニュー-->
  <div class="row">
    <div class="col-md-2">
      <%= render 'recipes/side_menu', genres: @genres %>
    </div>
    
    <!--タイトル-->
    <div class="col-md-10 mt-3">
      <div class="title">
        <% if params[:genre_id] %>
        	<h3><%= @genre.name %> (<%= @all_recipes_count %>)</h3>
        <% elsif params[:tag_id] %>
          <h3><%= @recipe_tag %>(<%= @all_recipes_count %>)</h3>
        <% else %>
        	<h3>全レシピ (<%= @all_recipes_count %>)</h3>
        <% end %>
      </div>
      
      <!--レシピ一覧-->
      <div class="row">
        <% @recipes.each do |recipe| %>
          <div class="col-md-4">
            <div class="items">
              <%= link_to recipe_path(recipe.id) do %>
                <%= attachment_image_tag recipe,:recipe_image, class: "img-fluid", fallback: "no_image.jpg" %>
              <% end %>
              <div class="mt-3 mb-5 d-flex justify-content-between">
                <h5><%= link_to recipe.name, recipe_path(recipe.id) %></h5>
                
                <!--お気に入り機能-->
                <div id="favorite_<%= recipe.id %>">
                  <%= link_to recipes_favorite_path(id: recipe.id), remote: true do %>
                    <% if recipe.favorite %>
                      <i class="fas fa-heart text-danger"></i>
                    <% else %>
                      <i class="far fa-heart"></i>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!--ページ-->
<%= paginate @recipes %>

app/views/recipes/new.html.erb
<!--エラーメッセージ-->
<% if @recipe.errors.any? %>
  <div class="container mt-5">
    <div class="form">
      <div class="error-box p-3">
        <h5 class=text-danger><%= @recipe.errors.count %>件のエラーが発生しました</h5>
        <ul class="ml-4">
          <% @recipe.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

<div class="container mt-5">
  <div class="row mb-3">
    <div class="col-md-12">
      <h3>New Recipe</h3>

      <%= form_with model: @recipe, local:true do |f| %>
        <div class="form">
          <div class="form-group mb-4">
            <%= f.label :name %><br/>
            <%= f.text_field :name, class: "form-control" %>
          </div>

          <div class="form-group mb-4">
            <%= f.label :recipe_image %><br/>
            <%= f.attachment_field :recipe_image %>
          </div>

          <div class="form-group mb-4">
            <%= f.label :ingredient %>
            <%= f.hidden_field :ingredient, id: :ingredient, class: "form-control" %>
            <trix-editor input="ingredient"></trix-editor>
          </div>

          <div class="form-group mb-4">
            <%= f.label :method %>
            <%= f.hidden_field :method, id: :method, class: "form-control" %>
            <trix-editor input="method"></trix-editor>
          </div>

          <div class="field mb-4">
            <%= f.label :serve %>
            <%= f.select :serve, options_for_select((1..10).to_a)%>
          </div>

          <div class="form-group mb-4">
            <%= f.label :cooking_time %>
            <%= f.select :cooking_time, Recipe.cooking_times.keys, {prompt: "Select"} %>
          </div>

          <div class="form-group mb-4">
            <div id="star" class="form-group">
              <%= f.label :rate %>
              <%= f.hidden_field :rate, class:"form-control" %>
            </div>
            <script>
              $('#star').raty({
                size     : 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn :  '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                scoreName: 'recipe[rate]',
                half: true,
              });
            </script>
          </div>

          <div class="form-group mb-4">
            <%= f.label :memo %>
            <%= f.hidden_field :memo, id: :memo, class: "form-control" %>
            <trix-editor input="memo", placeholder= "コツや注意書きなど"></trix-editor>
          </div>

          <div class="form-group mb-4">
            <%= f.label :genre_id %><br/>
            <%= f.select :genre_id, @genre_list, include_blank: "Select" %>
          </div>

          <div class="form-group mb-4">
            <%= f.label :tag_name %><br/>
            <%= f.text_field :tag_name, class: "form-control", placeholder: "グルテンフリー バター不使用 など　(タグを複数つけるには半角スペースで区切ってください)" %>
          </div>
        </div>

        <div class="create-btn">
          <%= f.submit '保存', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!--トップに戻るボタン-->
<span id="back">
  <a href="#">
    <i class="fas fa-arrow-circle-up arrow"></i>
  </a>
</span>

app/views/recipes/show.html.erb
<div class="container mt-5">
  <%= link_to "Back", recipes_path, class:"btn btn-sm btn-primary"%>

  <div class="row">
    <div class="recipe-headding mb-3 ml-3">
      <h1><%= @recipe.name %></h1>
    </div>
  </div>

  <div class="row mb-5">
    <div class="col-md-5">
      <%= link_to recipe_path(@recipe.id) do %>
        <%= attachment_image_tag @recipe,:recipe_image, class: 'img-fluid',  fallback: "no_image.jpg" %>
      <% end %>
    </div>

    <div class="col-md-3 my-3 my-md-0">
      <div class="recipe-ingredients">
        <h3>材料</h3>
          <%= sanitize @recipe.ingredient, tags:%w(strong em p br div ul ol li) %>
      </div>
    </div>

    <!--詳細-->
    <div class="col-md-4">
      <div class="recipe-details">
        <div class="recipe-detail-serves">
          <span class="detail">
            <%= @recipe.serve%>人分
          </span>
        </div>

        <div class="recipe-detail-serves">
          <span class="detail">
            <i class="fas fa-clock"></i>
          </span>
          <%= @recipe.cooking_time %>
        </div>

        <div class="recipe-detail-serves mb-4">
          <span class="detail">
            難易度
          </span>
          <div id="star-rate<%= @recipe.id %>"></div>
          <script>
            $('#star-rate<%= @recipe.id %>').empty();
            $('#star-rate<%= @recipe.id %>').raty({
              size: 36,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= @recipe.rate %>,
            });
          </script>
        </div>

        <div class="tag-list mb-4">
          <i class="fas fa-tags"></i>
            <% @recipe.recipe_tags.each do |recipe_tag| %>
              <%= link_to recipe_tag.tag.tag_name, recipes_path(tag_id: recipe_tag.tag.id) %>
            <% end %>
        </div>

        <div class="memo mb-4">
          <h4>メモ</h4>
            <%= sanitize @recipe.memo, tags:%w(strong em p br div ul ol li) %>
        </div>

        <div class="views">
          <h4>閲覧数</h4>
            <%= @recipe.impressionist_count %>
        </div>
      </div>

      <%= link_to "", edit_recipe_path, class:"fas fa-edit btn btn-lg btn-primary" %></td>
      <%= link_to "", recipe_path(@recipe),method: :delete, class:"fas fa-trash btn btn-lg btn-primary", "data-confirm" =>"本当に消しますか?" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="method mb-3">
        <h3>作り方</h3>
          <%= sanitize @recipe.method, tags:%w(strong em p br div ul ol li) %>
      </div>
    </div>
  </div>
</div>

<!--トップに戻るボタン-->
<span id="back">
  <a href="#">
    <i class="fas fa-arrow-circle-up arrow"></i>
  </a>
</span>