config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
    root 'homes#top'
    get '/about' => 'homes#about'
    get '/search' => 'searches#search'
    get '/recipes/favorite' => 'recipes#favorite'
    resources :recipes, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :show]

    get 'unsubscribe/' => 'users#unsubscribe', as: 'confirm_unsubscribe'
    patch ':id/withdraw/' => 'users#withdraw', as: 'withdraw_user'
    put 'withdraw/' => 'users#withdraw'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :recipes, dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_inactive_user, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def reject_inactive_user
    @user = current_user
    if @user
      if @user.valid_password?(params[:user][:password]) && !@user.is_valid
        reset_session
        redirect_to new_user_session_path
      end
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @favorite_recipes = current_user.recipes.where(favorite: true)
    @recipes = current_user.recipes.order(impressions_count: :desc).limit(5)
    # デプロイ用
    order_random = "RANDOM()"
    if Rails.env.production?
      order_random = "RAND()"
    end

    @random_recipes = current_user.recipes.order(order_random).limit(1)
  end

  def show
    @all_recipes_count = current_user.recipes.count
    @favorite_recipes_count = current_user.recipes.where(favorite: true).count
    @array = []
    Genre.all.each do |genre|
      @array.push([genre.name, genre.recipes.where(user_id: current_user.id).count])
    end
  end
  
  def unsubscribe
    @user = current_user
  end

  def withdraw
    @user = current_user
    @user.update(is_valid: false)
    reset_session
    flash[:notice] = "退会しました。"
    redirect_to root_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="home-visual">
  <div class="home-visual-content">
    <p class="home-visual-text">
       Welcome back<br/>
       <%= current_user.name %>さん
    </p>
  </div>
</div>

<div class="container mt-5">
  <!--MENU-->
  <div class="row">
    <div class="col-md-4 menu-box">
      <div class="index-button">
        <%= link_to "レシピを追加", new_recipe_path, class: "btn-circle-flat" %>
      </div>
    </div>
    <div class="col-md-4 menu-box">
      <% @random_recipes.each do |random_recipe| %>
        <%= link_to "今日は何作る？", recipe_path(random_recipe.id), class: "btn-circle-flat" %>
      <% end %>
    </div>
    <div class="col-md-4 menu-box">
      <%= link_to "ジャンルで探す", recipes_path, class: "btn-circle-flat" %>
    </div>
  </div>
  
  <!--閲覧数ランキング-->
  <div class="row my-5">
    <div class="col-md-12">
      <div class="top5 mb-3">
        <h3>閲覧数 Top 5</h3>
      </div>
      <div class="sliderArea">
        <div class="item-image-slide slider">
          <% @recipes.each.with_index(1) do |recipe, i| %>
            <%= link_to recipe_path(recipe.id) do %>
              <h4 class="slick-text">第<%= i %>位</h4>
              <%= attachment_image_tag recipe,:recipe_image, class: "slick-image", fallback: "no_image.jpg" %>
              <h4 class="slick-text"><%= recipe.name %></h4>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  
  <!--お気に入りレシピ一覧-->
  <div class="row mb-3">
    <div class="col-md-12">
        <h3>お気に入りレシピ</h3>
    </div>
  </div>
  
  <div class="row">
    <% @favorite_recipes.each do |favorite_recipe| %>
      <div class="col-md-3">
        <div class="items">
          <%= link_to recipe_path(favorite_recipe.id) do %>
            <%= attachment_image_tag favorite_recipe,:recipe_image, class: "img-fluid", fallback: "no_image.jpg" %>
          <% end %>
          <div class="mt-3 mb-5 d-flex justify-content-between">
            <div>
              <h5><%= link_to favorite_recipe.name, recipe_path(favorite_recipe.id) %></h5>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!--トップに戻るボタン-->
<span id="back">
  <a href="#">
    <i class="fas fa-arrow-circle-up arrow"></i>
  </a>
</span>

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-12">
      <h3>My page</h3>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-md-5">
      <h4>プロフィール</h4>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>名前</th>
            <td><%= current_user.name %></td>
          </tr>
          <tr>
            <th>Email</th>
            <td><%= current_user.email %></td>
          </tr>
        </thead>
      </table>

      <h4>データ</h4>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>総レシピ数</th>
            <td><%= @all_recipes_count%></td>
          </tr>
          <tr>
            <th>お気に入りレシピ数</th>
            <td><%= @favorite_recipes_count %></td>
          </tr>
        </thead>
      </table>
    </div>

    <!--ジャンル別円グラフ-->
    <div class="col-md-6">
      <div class="chart">
        <%= pie_chart @array, colors: ["#EAC879", "#E0E0D5", "#BBAAA1", "#E98291", "#B5BBD1", "#F3EFF0", "#644F4D", "#ECDECC", "#AAC7B0", "#92C8DC"] %>
      </div>
    </div>
  </div>

  <!--退会機能-->
  <div class="row">
    <div class="col-md-3">
      <%= link_to '退会する', confirm_unsubscribe_path, class:'btn btn-primary ml-5' %>
    </div>
  </div>
</div>

app/views/users/unsubscribe.html.erb
<div class = "container">
  <div class = "row">
    <div class="px-3 mx-auto mt-5">
      <h3 class="unsubscribe"><strong>本当に退会しますか？</strong></h3>
      <p class="unsubscribe">
        退会すると、<br>
        これまでのレシピが閲覧できなくなります。<br>
        退会する場合は、「退会する」をクリックしてください。<br>
      </p>
      <div class="mx-auto">
        <%= link_to '退会しない', users_path, class:'btn btn-primary offset-3' %>
        <%= link_to '退会する', withdraw_user_path(@user), method: :patch, class:'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>