config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
    root 'homes#top'
    get '/about' => 'homes#about'
    get '/search' => 'searches#search'
    get '/recipes/favorite' => 'recipes#favorite'
    resources :recipes, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :show]

    get 'unsubscribe/' => 'users#unsubscribe', as: 'confirm_unsubscribe'
    patch ':id/withdraw/' => 'users#withdraw', as: 'withdraw_user'
    put 'withdraw/' => 'users#withdraw'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sugarist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <h2><%= link_to 'Sugarist', root_path, class: 'nav-link text-dark logo' %></h2>
        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02"
                aria-expanded="false"
                aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav ml-auto ">
            <% if user_signed_in? %>
              <li class="nav-item ">
                <%= link_to "Home", users_path, class: 'fas fa-home nav-link text-dark nav-home' %>
              </li>
              <li class="nav-item">
                <%= link_to "Recipes", recipes_path, class: "fas fa-book-open nav-link text-dark nav-recipe" %>
              </li>
              <li class="nav-item">
                <%= link_to "New Recipe", new_recipe_path, class: "fas fa-pen nav-link text-dark nav-newpost" %>
              </li>
              <li class="nav-item">
                <%= link_to "My page", user_path(current_user.id), class: "fas fa-user nav-link text-dark nav-mypage" %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-dark nav-signout" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Home", root_path, class: "fas fa-home nav-link text-dark nav-home" %>
              </li>
              <li class="nav-item">
                <%= link_to "About", about_path, class: "fas fa-link nav-link text-dark nav-about" %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-dark nav-signup" %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign in", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-dark nav-signin" %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    
    <!--フラッシュメッセージ-->
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    
    <%= yield %>

    <footer>
      <p class="footer-text">© 2021 Yukino Shinji</p>
    </footer>
  </body>
</html>